apiVersion: v1
kind: Service
metadata:
  name: fake-ns-database-clusterip-vitaflow
  namespace: fake-ns
spec:
  type: ClusterIP
  selector:
    database: vitaflow
  ports:
    - port: 5432
      targetPort: 5432
      