apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fake-ns-database-pvc-vitaflow
  namespace: fake-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
